"""
Bloop Safe Circuit Builder
Constructs verified Qiskit QuantumCircuit instances from validated gate operations.
Strictly eliminates any dynamic execution, eval, or unvetted library calls.
"""

from typing import List, Tuple
from qiskit import QuantumCircuit
from backend.app.quantum.laboratory.circuits.validator import CircuitValidator
from backend.app.quantum.laboratory.models import GateDefinition, SupportedGate


class SafeCircuitBuilder:
    """Builds Qiskit quantum circuits in a strictly bounded, validated environment."""

    @classmethod
    def build(
        cls,
        num_qubits: int,
        operations: List[GateDefinition],
        add_measurements: bool = True,
    ) -> Tuple[QuantumCircuit, int, int]:
        """
        Constructs a QuantumCircuit.
        Returns:
            Tuple of (QuantumCircuit, circuit_depth, total_gates)
        """
        qc = QuantumCircuit(num_qubits, num_qubits, name="lab_circuit")

        for op in operations:
            g = op.gate.lower()
            target = op.target
            ctrl = op.control
            param = op.parameter

            if g == SupportedGate.H.value:
                qc.h(target)
            elif g == SupportedGate.X.value:
                qc.x(target)
            elif g == SupportedGate.Y.value:
                qc.y(target)
            elif g == SupportedGate.Z.value:
                qc.z(target)
            elif g == SupportedGate.S.value:
                qc.s(target)
            elif g == SupportedGate.T.value:
                qc.t(target)
            elif g == SupportedGate.RX.value:
                qc.rx(param if param is not None else 0.0, target)
            elif g == SupportedGate.RY.value:
                qc.ry(param if param is not None else 0.0, target)
            elif g == SupportedGate.RZ.value:
                qc.rz(param if param is not None else 0.0, target)
            elif g == SupportedGate.CX.value:
                qc.cx(ctrl if ctrl is not None else 0, target)
            elif g == SupportedGate.CZ.value:
                qc.cz(ctrl if ctrl is not None else 0, target)
            elif g == SupportedGate.SWAP.value:
                qc.swap(ctrl if ctrl is not None else 0, target)

        # Gate metrics before adding measurement overhead
        circuit_depth = qc.depth()
        total_gates = sum(qc.count_ops().values())

        # Validate depth guard
        CircuitValidator.validate_depth(circuit_depth)

        if add_measurements:
            qc.measure(range(num_qubits), range(num_qubits))

        return qc, circuit_depth, total_gates

    @classmethod
    def generate_ascii_diagram(cls, circuit: QuantumCircuit) -> str:
        """Renders formatted ASCII circuit wire diagram."""
        try:
            return str(circuit.draw(output="text"))
        except Exception:
            return f"QuantumCircuit({circuit.num_qubits} qubits)"

    @classmethod
    def export_qasm(cls, circuit: QuantumCircuit) -> str:
        """Exports sanitized OpenQASM 2.0 representation."""
        try:
            from qiskit.qasm2 import dumps
            return dumps(circuit)
        except Exception:
            try:
                return circuit.qasm()
            except Exception:
                return "// OpenQASM 2.0 generated by Bloop Quantum Laboratory\n"
