"""
Audio Access Control & Ownership Security Tests
Verifies that audio streaming and download endpoints enforce user ownership:
- Non-owner users are strictly rejected with HTTP 403 Forbidden.
- Unauthenticated users cannot access private generations.
- Legitimate owners can stream and download.
- Range requests return HTTP 206 Partial Content.
- Path traversal attacks are mitigated.
"""

import os
import pytest
from fastapi.testclient import TestClient

from backend.app.core.security import create_access_token
from backend.app.models.speech_generation import SpeechGeneration
from backend.app.models.user import User
from backend.app.services.audio.delivery import AudioDeliveryService


@pytest.fixture
def test_users_and_generations(db_session):
    """Creates two distinct users and an audio generation owned by User A."""
    import uuid
    uid = uuid.uuid4().hex[:8]

    # User A
    user_a = User(
        email=f"user_a_{uid}@bloop.ai",
        hashed_password="hash-a-1234567890abcdef",
        full_name="User Alpha",
        is_active=True,
    )
    # User B
    user_b = User(
        email=f"user_b_{uid}@bloop.ai",
        hashed_password="hash-b-1234567890abcdef",
        full_name="User Beta",
        is_active=True,
    )
    db_session.add(user_a)
    db_session.add(user_b)
    db_session.commit()
    db_session.refresh(user_a)
    db_session.refresh(user_b)

    # Store a physical audio file
    delivery = AudioDeliveryService()
    audio_content = b"\xff\xfb\x90\x44" * 50
    filename = delivery.store_temporary_audio(audio_content, extension="mp3")

    # SpeechGeneration owned by User A
    gen_a = SpeechGeneration(
        user_id=user_a.id,
        text="Confidential speech generated by User Alpha.",
        char_count=45,
        word_count=6,
        language_code="en-US",
        voice_id="normal-female",
        audio_filename=filename,
        duration_seconds=3.0,
        file_size_bytes=len(audio_content),
        provider="elevenlabs",
        status="completed",
    )
    db_session.add(gen_a)
    db_session.commit()
    db_session.refresh(gen_a)

    token_a = create_access_token(subject=str(user_a.id))
    token_b = create_access_token(subject=str(user_b.id))

    yield {
        "user_a": user_a,
        "user_b": user_b,
        "token_a": token_a,
        "token_b": token_b,
        "gen_a": gen_a,
        "filename": filename,
    }

    # Clean up
    try:
        delivery.delete_audio_file(filename)
        db_session.delete(gen_a)
        db_session.delete(user_a)
        db_session.delete(user_b)
        db_session.commit()
    except Exception:
        db_session.rollback()


class TestAudioOwnershipAccessControl:
    """Verifies that audio endpoints reject non-owners and authorize legitimate owners."""

    def test_non_owner_cannot_stream_audio(self, client: TestClient, test_users_and_generations):
        data = test_users_and_generations
        gen_id = data["gen_a"].id
        token_b = data["token_b"]  # User B's token

        # User B attempts to access User A's audio by generation_id
        res = client.get(
            f"/api/v1/tts/{gen_id}/audio",
            headers={"Authorization": f"Bearer {token_b}"},
        )
        assert res.status_code == 403
        assert res.json()["error"]["code"] == "GENERATION_ACCESS_DENIED"

        # User B attempts by filename
        filename = data["filename"]
        res_fn = client.get(
            f"/api/v1/tts/audio/{filename}",
            headers={"Authorization": f"Bearer {token_b}"},
        )
        assert res_fn.status_code == 403
        assert res_fn.json()["error"]["code"] == "GENERATION_ACCESS_DENIED"

    def test_non_owner_cannot_download_audio(self, client: TestClient, test_users_and_generations):
        data = test_users_and_generations
        gen_id = data["gen_a"].id
        token_b = data["token_b"]

        res = client.get(
            f"/api/v1/tts/{gen_id}/download",
            headers={"Authorization": f"Bearer {token_b}"},
        )
        assert res.status_code == 403
        assert res.json()["error"]["code"] == "GENERATION_ACCESS_DENIED"

    def test_unauthenticated_request_to_private_generation_rejected(
        self, client: TestClient, test_users_and_generations
    ):
        data = test_users_and_generations
        gen_id = data["gen_a"].id

        # Anonymous request without Authorization header
        res = client.get(f"/api/v1/tts/{gen_id}/audio")
        assert res.status_code in (401, 403)

    def test_owner_can_stream_audio_and_range_seek(self, client: TestClient, test_users_and_generations):
        data = test_users_and_generations
        gen_id = data["gen_a"].id
        token_a = data["token_a"]  # User A's token

        # Full stream request
        res = client.get(
            f"/api/v1/tts/{gen_id}/audio",
            headers={"Authorization": f"Bearer {token_a}"},
        )
        assert res.status_code == 200
        assert res.headers["accept-ranges"] == "bytes"
        assert res.headers["content-type"] in ["audio/mpeg", "audio/wav"]

        # HTTP Range request (seeking first 100 bytes)
        range_res = client.get(
            f"/api/v1/tts/{gen_id}/audio",
            headers={
                "Authorization": f"Bearer {token_a}",
                "Range": "bytes=0-99",
            },
        )
        assert range_res.status_code == 206
        assert "bytes 0-99/" in range_res.headers["content-range"]
        assert len(range_res.content) == 100

    def test_owner_can_download_with_attachment_header(self, client: TestClient, test_users_and_generations):
        data = test_users_and_generations
        gen_id = data["gen_a"].id
        token_a = data["token_a"]

        res = client.get(
            f"/api/v1/tts/{gen_id}/download",
            headers={"Authorization": f"Bearer {token_a}"},
        )
        assert res.status_code == 200
        assert f'attachment; filename="bloop-speech-{gen_id}.mp3"' in res.headers["content-disposition"]
        assert len(res.content) > 0
